apiVersion: v1
kind: ConfigMap
metadata:
  name: axiom-config
  namespace: axiom-prod
data:
  groq_api_url: "https://api.groq.com/openai/v1/chat/completions"
  frontend_url: "https://axiom.soempit.com"
