// Code generated by ent, DO NOT EDIT.

package userinvitation

import (
	"go-backend-template/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldEQ(FieldUpdatedAt, v))
}

// InviteURL applies equality check predicate on the "invite_url" field. It's identical to InviteURLEQ.
func InviteURL(v string) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldEQ(FieldInviteURL, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldLTE(FieldUpdatedAt, v))
}

// InviteURLEQ applies the EQ predicate on the "invite_url" field.
func InviteURLEQ(v string) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldEQ(FieldInviteURL, v))
}

// InviteURLNEQ applies the NEQ predicate on the "invite_url" field.
func InviteURLNEQ(v string) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldNEQ(FieldInviteURL, v))
}

// InviteURLIn applies the In predicate on the "invite_url" field.
func InviteURLIn(vs ...string) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldIn(FieldInviteURL, vs...))
}

// InviteURLNotIn applies the NotIn predicate on the "invite_url" field.
func InviteURLNotIn(vs ...string) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldNotIn(FieldInviteURL, vs...))
}

// InviteURLGT applies the GT predicate on the "invite_url" field.
func InviteURLGT(v string) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldGT(FieldInviteURL, v))
}

// InviteURLGTE applies the GTE predicate on the "invite_url" field.
func InviteURLGTE(v string) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldGTE(FieldInviteURL, v))
}

// InviteURLLT applies the LT predicate on the "invite_url" field.
func InviteURLLT(v string) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldLT(FieldInviteURL, v))
}

// InviteURLLTE applies the LTE predicate on the "invite_url" field.
func InviteURLLTE(v string) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldLTE(FieldInviteURL, v))
}

// InviteURLContains applies the Contains predicate on the "invite_url" field.
func InviteURLContains(v string) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldContains(FieldInviteURL, v))
}

// InviteURLHasPrefix applies the HasPrefix predicate on the "invite_url" field.
func InviteURLHasPrefix(v string) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldHasPrefix(FieldInviteURL, v))
}

// InviteURLHasSuffix applies the HasSuffix predicate on the "invite_url" field.
func InviteURLHasSuffix(v string) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldHasSuffix(FieldInviteURL, v))
}

// InviteURLEqualFold applies the EqualFold predicate on the "invite_url" field.
func InviteURLEqualFold(v string) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldEqualFold(FieldInviteURL, v))
}

// InviteURLContainsFold applies the ContainsFold predicate on the "invite_url" field.
func InviteURLContainsFold(v string) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldContainsFold(FieldInviteURL, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.UserInvitation {
	return predicate.UserInvitation(sql.FieldNotIn(FieldStatus, vs...))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserInvitation {
	return predicate.UserInvitation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserInvitation {
	return predicate.UserInvitation(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserInvitation) predicate.UserInvitation {
	return predicate.UserInvitation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserInvitation) predicate.UserInvitation {
	return predicate.UserInvitation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserInvitation) predicate.UserInvitation {
	return predicate.UserInvitation(sql.NotPredicates(p))
}
