// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-backend-template/ent/actionmodel"
	"go-backend-template/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ActionModelUpdate is the builder for updating ActionModel entities.
type ActionModelUpdate struct {
	config
	hooks    []Hook
	mutation *ActionModelMutation
}

// Where appends a list predicates to the ActionModelUpdate builder.
func (_u *ActionModelUpdate) Where(ps ...predicate.ActionModel) *ActionModelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *ActionModelUpdate) SetProjectID(v string) *ActionModelUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *ActionModelUpdate) SetNillableProjectID(v *string) *ActionModelUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ActionModelUpdate) SetName(v string) *ActionModelUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ActionModelUpdate) SetNillableName(v *string) *ActionModelUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ActionModelUpdate) SetDescription(v string) *ActionModelUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ActionModelUpdate) SetNillableDescription(v *string) *ActionModelUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetParameters sets the "parameters" field.
func (_u *ActionModelUpdate) SetParameters(v map[string]interface{}) *ActionModelUpdate {
	_u.mutation.SetParameters(v)
	return _u
}

// SetRules sets the "rules" field.
func (_u *ActionModelUpdate) SetRules(v map[string]interface{}) *ActionModelUpdate {
	_u.mutation.SetRules(v)
	return _u
}

// SetRequiredFeature sets the "required_feature" field.
func (_u *ActionModelUpdate) SetRequiredFeature(v string) *ActionModelUpdate {
	_u.mutation.SetRequiredFeature(v)
	return _u
}

// SetNillableRequiredFeature sets the "required_feature" field if the given value is not nil.
func (_u *ActionModelUpdate) SetNillableRequiredFeature(v *string) *ActionModelUpdate {
	if v != nil {
		_u.SetRequiredFeature(*v)
	}
	return _u
}

// ClearRequiredFeature clears the value of the "required_feature" field.
func (_u *ActionModelUpdate) ClearRequiredFeature() *ActionModelUpdate {
	_u.mutation.ClearRequiredFeature()
	return _u
}

// SetVersion sets the "version" field.
func (_u *ActionModelUpdate) SetVersion(v int) *ActionModelUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ActionModelUpdate) SetNillableVersion(v *int) *ActionModelUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *ActionModelUpdate) AddVersion(v int) *ActionModelUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the ActionModelMutation object of the builder.
func (_u *ActionModelUpdate) Mutation() *ActionModelMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ActionModelUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ActionModelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ActionModelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ActionModelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ActionModelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(actionmodel.Table, actionmodel.Columns, sqlgraph.NewFieldSpec(actionmodel.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(actionmodel.FieldProjectID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(actionmodel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(actionmodel.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Parameters(); ok {
		_spec.SetField(actionmodel.FieldParameters, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Rules(); ok {
		_spec.SetField(actionmodel.FieldRules, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.RequiredFeature(); ok {
		_spec.SetField(actionmodel.FieldRequiredFeature, field.TypeString, value)
	}
	if _u.mutation.RequiredFeatureCleared() {
		_spec.ClearField(actionmodel.FieldRequiredFeature, field.TypeString)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(actionmodel.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(actionmodel.FieldVersion, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{actionmodel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ActionModelUpdateOne is the builder for updating a single ActionModel entity.
type ActionModelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ActionModelMutation
}

// SetProjectID sets the "project_id" field.
func (_u *ActionModelUpdateOne) SetProjectID(v string) *ActionModelUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *ActionModelUpdateOne) SetNillableProjectID(v *string) *ActionModelUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ActionModelUpdateOne) SetName(v string) *ActionModelUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ActionModelUpdateOne) SetNillableName(v *string) *ActionModelUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ActionModelUpdateOne) SetDescription(v string) *ActionModelUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ActionModelUpdateOne) SetNillableDescription(v *string) *ActionModelUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetParameters sets the "parameters" field.
func (_u *ActionModelUpdateOne) SetParameters(v map[string]interface{}) *ActionModelUpdateOne {
	_u.mutation.SetParameters(v)
	return _u
}

// SetRules sets the "rules" field.
func (_u *ActionModelUpdateOne) SetRules(v map[string]interface{}) *ActionModelUpdateOne {
	_u.mutation.SetRules(v)
	return _u
}

// SetRequiredFeature sets the "required_feature" field.
func (_u *ActionModelUpdateOne) SetRequiredFeature(v string) *ActionModelUpdateOne {
	_u.mutation.SetRequiredFeature(v)
	return _u
}

// SetNillableRequiredFeature sets the "required_feature" field if the given value is not nil.
func (_u *ActionModelUpdateOne) SetNillableRequiredFeature(v *string) *ActionModelUpdateOne {
	if v != nil {
		_u.SetRequiredFeature(*v)
	}
	return _u
}

// ClearRequiredFeature clears the value of the "required_feature" field.
func (_u *ActionModelUpdateOne) ClearRequiredFeature() *ActionModelUpdateOne {
	_u.mutation.ClearRequiredFeature()
	return _u
}

// SetVersion sets the "version" field.
func (_u *ActionModelUpdateOne) SetVersion(v int) *ActionModelUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ActionModelUpdateOne) SetNillableVersion(v *int) *ActionModelUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *ActionModelUpdateOne) AddVersion(v int) *ActionModelUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the ActionModelMutation object of the builder.
func (_u *ActionModelUpdateOne) Mutation() *ActionModelMutation {
	return _u.mutation
}

// Where appends a list predicates to the ActionModelUpdate builder.
func (_u *ActionModelUpdateOne) Where(ps ...predicate.ActionModel) *ActionModelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ActionModelUpdateOne) Select(field string, fields ...string) *ActionModelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ActionModel entity.
func (_u *ActionModelUpdateOne) Save(ctx context.Context) (*ActionModel, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ActionModelUpdateOne) SaveX(ctx context.Context) *ActionModel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ActionModelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ActionModelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ActionModelUpdateOne) sqlSave(ctx context.Context) (_node *ActionModel, err error) {
	_spec := sqlgraph.NewUpdateSpec(actionmodel.Table, actionmodel.Columns, sqlgraph.NewFieldSpec(actionmodel.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ActionModel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, actionmodel.FieldID)
		for _, f := range fields {
			if !actionmodel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != actionmodel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(actionmodel.FieldProjectID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(actionmodel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(actionmodel.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Parameters(); ok {
		_spec.SetField(actionmodel.FieldParameters, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Rules(); ok {
		_spec.SetField(actionmodel.FieldRules, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.RequiredFeature(); ok {
		_spec.SetField(actionmodel.FieldRequiredFeature, field.TypeString, value)
	}
	if _u.mutation.RequiredFeatureCleared() {
		_spec.ClearField(actionmodel.FieldRequiredFeature, field.TypeString)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(actionmodel.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(actionmodel.FieldVersion, field.TypeInt, value)
	}
	_node = &ActionModel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{actionmodel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
