// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-backend-template/ent/actionmodel"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ActionModelCreate is the builder for creating a ActionModel entity.
type ActionModelCreate struct {
	config
	mutation *ActionModelMutation
	hooks    []Hook
}

// SetProjectID sets the "project_id" field.
func (_c *ActionModelCreate) SetProjectID(v string) *ActionModelCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ActionModelCreate) SetName(v string) *ActionModelCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ActionModelCreate) SetDescription(v string) *ActionModelCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetParameters sets the "parameters" field.
func (_c *ActionModelCreate) SetParameters(v map[string]interface{}) *ActionModelCreate {
	_c.mutation.SetParameters(v)
	return _c
}

// SetRules sets the "rules" field.
func (_c *ActionModelCreate) SetRules(v map[string]interface{}) *ActionModelCreate {
	_c.mutation.SetRules(v)
	return _c
}

// SetRequiredFeature sets the "required_feature" field.
func (_c *ActionModelCreate) SetRequiredFeature(v string) *ActionModelCreate {
	_c.mutation.SetRequiredFeature(v)
	return _c
}

// SetNillableRequiredFeature sets the "required_feature" field if the given value is not nil.
func (_c *ActionModelCreate) SetNillableRequiredFeature(v *string) *ActionModelCreate {
	if v != nil {
		_c.SetRequiredFeature(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *ActionModelCreate) SetVersion(v int) *ActionModelCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *ActionModelCreate) SetNillableVersion(v *int) *ActionModelCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// Mutation returns the ActionModelMutation object of the builder.
func (_c *ActionModelCreate) Mutation() *ActionModelMutation {
	return _c.mutation
}

// Save creates the ActionModel in the database.
func (_c *ActionModelCreate) Save(ctx context.Context) (*ActionModel, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ActionModelCreate) SaveX(ctx context.Context) *ActionModel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ActionModelCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ActionModelCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ActionModelCreate) defaults() {
	if _, ok := _c.mutation.Version(); !ok {
		v := actionmodel.DefaultVersion
		_c.mutation.SetVersion(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ActionModelCreate) check() error {
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "ActionModel.project_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ActionModel.name"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "ActionModel.description"`)}
	}
	if _, ok := _c.mutation.Parameters(); !ok {
		return &ValidationError{Name: "parameters", err: errors.New(`ent: missing required field "ActionModel.parameters"`)}
	}
	if _, ok := _c.mutation.Rules(); !ok {
		return &ValidationError{Name: "rules", err: errors.New(`ent: missing required field "ActionModel.rules"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "ActionModel.version"`)}
	}
	return nil
}

func (_c *ActionModelCreate) sqlSave(ctx context.Context) (*ActionModel, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ActionModelCreate) createSpec() (*ActionModel, *sqlgraph.CreateSpec) {
	var (
		_node = &ActionModel{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(actionmodel.Table, sqlgraph.NewFieldSpec(actionmodel.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ProjectID(); ok {
		_spec.SetField(actionmodel.FieldProjectID, field.TypeString, value)
		_node.ProjectID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(actionmodel.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(actionmodel.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Parameters(); ok {
		_spec.SetField(actionmodel.FieldParameters, field.TypeJSON, value)
		_node.Parameters = value
	}
	if value, ok := _c.mutation.Rules(); ok {
		_spec.SetField(actionmodel.FieldRules, field.TypeJSON, value)
		_node.Rules = value
	}
	if value, ok := _c.mutation.RequiredFeature(); ok {
		_spec.SetField(actionmodel.FieldRequiredFeature, field.TypeString, value)
		_node.RequiredFeature = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(actionmodel.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	return _node, _spec
}

// ActionModelCreateBulk is the builder for creating many ActionModel entities in bulk.
type ActionModelCreateBulk struct {
	config
	err      error
	builders []*ActionModelCreate
}

// Save creates the ActionModel entities in the database.
func (_c *ActionModelCreateBulk) Save(ctx context.Context) ([]*ActionModel, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ActionModel, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ActionModelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ActionModelCreateBulk) SaveX(ctx context.Context) []*ActionModel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ActionModelCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ActionModelCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
