// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/Emmanuel-Soempit/axiom/ent/agent"
	"github.com/Emmanuel-Soempit/axiom/ent/auditrecord"
	"github.com/Emmanuel-Soempit/axiom/ent/feature"
	"github.com/Emmanuel-Soempit/axiom/ent/predicate"
	"github.com/Emmanuel-Soempit/axiom/ent/project"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AgentUpdate is the builder for updating Agent entities.
type AgentUpdate struct {
	config
	hooks    []Hook
	mutation *AgentMutation
}

// Where appends a list predicates to the AgentUpdate builder.
func (_u *AgentUpdate) Where(ps ...predicate.Agent) *AgentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentUpdate) SetUpdatedAt(v time.Time) *AgentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AgentUpdate) SetName(v string) *AgentUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableName(v *string) *AgentUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *AgentUpdate) SetSlug(v string) *AgentUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableSlug(v *string) *AgentUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *AgentUpdate) SetDescription(v string) *AgentUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableDescription(v *string) *AgentUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *AgentUpdate) ClearDescription() *AgentUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetSystemPrompt sets the "system_prompt" field.
func (_u *AgentUpdate) SetSystemPrompt(v string) *AgentUpdate {
	_u.mutation.SetSystemPrompt(v)
	return _u
}

// SetNillableSystemPrompt sets the "system_prompt" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableSystemPrompt(v *string) *AgentUpdate {
	if v != nil {
		_u.SetSystemPrompt(*v)
	}
	return _u
}

// ClearSystemPrompt clears the value of the "system_prompt" field.
func (_u *AgentUpdate) ClearSystemPrompt() *AgentUpdate {
	_u.mutation.ClearSystemPrompt()
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *AgentUpdate) SetProjectID(v string) *AgentUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableProjectID(v *string) *AgentUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetActive sets the "active" field.
func (_u *AgentUpdate) SetActive(v bool) *AgentUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableActive(v *bool) *AgentUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *AgentUpdate) SetProject(v *Project) *AgentUpdate {
	return _u.SetProjectID(v.ID)
}

// AddAuditRecordIDs adds the "audit_records" edge to the AuditRecord entity by IDs.
func (_u *AgentUpdate) AddAuditRecordIDs(ids ...int) *AgentUpdate {
	_u.mutation.AddAuditRecordIDs(ids...)
	return _u
}

// AddAuditRecords adds the "audit_records" edges to the AuditRecord entity.
func (_u *AgentUpdate) AddAuditRecords(v ...*AuditRecord) *AgentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAuditRecordIDs(ids...)
}

// AddFeatureIDs adds the "feature" edge to the Feature entity by IDs.
func (_u *AgentUpdate) AddFeatureIDs(ids ...int) *AgentUpdate {
	_u.mutation.AddFeatureIDs(ids...)
	return _u
}

// AddFeature adds the "feature" edges to the Feature entity.
func (_u *AgentUpdate) AddFeature(v ...*Feature) *AgentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFeatureIDs(ids...)
}

// Mutation returns the AgentMutation object of the builder.
func (_u *AgentUpdate) Mutation() *AgentMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *AgentUpdate) ClearProject() *AgentUpdate {
	_u.mutation.ClearProject()
	return _u
}

// ClearAuditRecords clears all "audit_records" edges to the AuditRecord entity.
func (_u *AgentUpdate) ClearAuditRecords() *AgentUpdate {
	_u.mutation.ClearAuditRecords()
	return _u
}

// RemoveAuditRecordIDs removes the "audit_records" edge to AuditRecord entities by IDs.
func (_u *AgentUpdate) RemoveAuditRecordIDs(ids ...int) *AgentUpdate {
	_u.mutation.RemoveAuditRecordIDs(ids...)
	return _u
}

// RemoveAuditRecords removes "audit_records" edges to AuditRecord entities.
func (_u *AgentUpdate) RemoveAuditRecords(v ...*AuditRecord) *AgentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAuditRecordIDs(ids...)
}

// ClearFeature clears all "feature" edges to the Feature entity.
func (_u *AgentUpdate) ClearFeature() *AgentUpdate {
	_u.mutation.ClearFeature()
	return _u
}

// RemoveFeatureIDs removes the "feature" edge to Feature entities by IDs.
func (_u *AgentUpdate) RemoveFeatureIDs(ids ...int) *AgentUpdate {
	_u.mutation.RemoveFeatureIDs(ids...)
	return _u
}

// RemoveFeature removes "feature" edges to Feature entities.
func (_u *AgentUpdate) RemoveFeature(v ...*Feature) *AgentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFeatureIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AgentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AgentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := agent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := agent.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Agent.name": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Agent.project"`)
	}
	return nil
}

func (_u *AgentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agent.Table, agent.Columns, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(agent.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(agent.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(agent.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(agent.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.SystemPrompt(); ok {
		_spec.SetField(agent.FieldSystemPrompt, field.TypeString, value)
	}
	if _u.mutation.SystemPromptCleared() {
		_spec.ClearField(agent.FieldSystemPrompt, field.TypeString)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(agent.FieldActive, field.TypeBool, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agent.ProjectTable,
			Columns: []string{agent.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agent.ProjectTable,
			Columns: []string{agent.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AuditRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.AuditRecordsTable,
			Columns: []string{agent.AuditRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditrecord.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAuditRecordsIDs(); len(nodes) > 0 && !_u.mutation.AuditRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.AuditRecordsTable,
			Columns: []string{agent.AuditRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditrecord.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuditRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.AuditRecordsTable,
			Columns: []string{agent.AuditRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditrecord.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FeatureCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.FeatureTable,
			Columns: []string{agent.FeatureColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(feature.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFeatureIDs(); len(nodes) > 0 && !_u.mutation.FeatureCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.FeatureTable,
			Columns: []string{agent.FeatureColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(feature.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FeatureIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.FeatureTable,
			Columns: []string{agent.FeatureColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(feature.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AgentUpdateOne is the builder for updating a single Agent entity.
type AgentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentUpdateOne) SetUpdatedAt(v time.Time) *AgentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AgentUpdateOne) SetName(v string) *AgentUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableName(v *string) *AgentUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *AgentUpdateOne) SetSlug(v string) *AgentUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableSlug(v *string) *AgentUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *AgentUpdateOne) SetDescription(v string) *AgentUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableDescription(v *string) *AgentUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *AgentUpdateOne) ClearDescription() *AgentUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetSystemPrompt sets the "system_prompt" field.
func (_u *AgentUpdateOne) SetSystemPrompt(v string) *AgentUpdateOne {
	_u.mutation.SetSystemPrompt(v)
	return _u
}

// SetNillableSystemPrompt sets the "system_prompt" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableSystemPrompt(v *string) *AgentUpdateOne {
	if v != nil {
		_u.SetSystemPrompt(*v)
	}
	return _u
}

// ClearSystemPrompt clears the value of the "system_prompt" field.
func (_u *AgentUpdateOne) ClearSystemPrompt() *AgentUpdateOne {
	_u.mutation.ClearSystemPrompt()
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *AgentUpdateOne) SetProjectID(v string) *AgentUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableProjectID(v *string) *AgentUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetActive sets the "active" field.
func (_u *AgentUpdateOne) SetActive(v bool) *AgentUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableActive(v *bool) *AgentUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *AgentUpdateOne) SetProject(v *Project) *AgentUpdateOne {
	return _u.SetProjectID(v.ID)
}

// AddAuditRecordIDs adds the "audit_records" edge to the AuditRecord entity by IDs.
func (_u *AgentUpdateOne) AddAuditRecordIDs(ids ...int) *AgentUpdateOne {
	_u.mutation.AddAuditRecordIDs(ids...)
	return _u
}

// AddAuditRecords adds the "audit_records" edges to the AuditRecord entity.
func (_u *AgentUpdateOne) AddAuditRecords(v ...*AuditRecord) *AgentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAuditRecordIDs(ids...)
}

// AddFeatureIDs adds the "feature" edge to the Feature entity by IDs.
func (_u *AgentUpdateOne) AddFeatureIDs(ids ...int) *AgentUpdateOne {
	_u.mutation.AddFeatureIDs(ids...)
	return _u
}

// AddFeature adds the "feature" edges to the Feature entity.
func (_u *AgentUpdateOne) AddFeature(v ...*Feature) *AgentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFeatureIDs(ids...)
}

// Mutation returns the AgentMutation object of the builder.
func (_u *AgentUpdateOne) Mutation() *AgentMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *AgentUpdateOne) ClearProject() *AgentUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// ClearAuditRecords clears all "audit_records" edges to the AuditRecord entity.
func (_u *AgentUpdateOne) ClearAuditRecords() *AgentUpdateOne {
	_u.mutation.ClearAuditRecords()
	return _u
}

// RemoveAuditRecordIDs removes the "audit_records" edge to AuditRecord entities by IDs.
func (_u *AgentUpdateOne) RemoveAuditRecordIDs(ids ...int) *AgentUpdateOne {
	_u.mutation.RemoveAuditRecordIDs(ids...)
	return _u
}

// RemoveAuditRecords removes "audit_records" edges to AuditRecord entities.
func (_u *AgentUpdateOne) RemoveAuditRecords(v ...*AuditRecord) *AgentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAuditRecordIDs(ids...)
}

// ClearFeature clears all "feature" edges to the Feature entity.
func (_u *AgentUpdateOne) ClearFeature() *AgentUpdateOne {
	_u.mutation.ClearFeature()
	return _u
}

// RemoveFeatureIDs removes the "feature" edge to Feature entities by IDs.
func (_u *AgentUpdateOne) RemoveFeatureIDs(ids ...int) *AgentUpdateOne {
	_u.mutation.RemoveFeatureIDs(ids...)
	return _u
}

// RemoveFeature removes "feature" edges to Feature entities.
func (_u *AgentUpdateOne) RemoveFeature(v ...*Feature) *AgentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFeatureIDs(ids...)
}

// Where appends a list predicates to the AgentUpdate builder.
func (_u *AgentUpdateOne) Where(ps ...predicate.Agent) *AgentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AgentUpdateOne) Select(field string, fields ...string) *AgentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Agent entity.
func (_u *AgentUpdateOne) Save(ctx context.Context) (*Agent, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentUpdateOne) SaveX(ctx context.Context) *Agent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AgentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := agent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := agent.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Agent.name": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Agent.project"`)
	}
	return nil
}

func (_u *AgentUpdateOne) sqlSave(ctx context.Context) (_node *Agent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agent.Table, agent.Columns, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Agent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agent.FieldID)
		for _, f := range fields {
			if !agent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(agent.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(agent.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(agent.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(agent.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.SystemPrompt(); ok {
		_spec.SetField(agent.FieldSystemPrompt, field.TypeString, value)
	}
	if _u.mutation.SystemPromptCleared() {
		_spec.ClearField(agent.FieldSystemPrompt, field.TypeString)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(agent.FieldActive, field.TypeBool, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agent.ProjectTable,
			Columns: []string{agent.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agent.ProjectTable,
			Columns: []string{agent.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AuditRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.AuditRecordsTable,
			Columns: []string{agent.AuditRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditrecord.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAuditRecordsIDs(); len(nodes) > 0 && !_u.mutation.AuditRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.AuditRecordsTable,
			Columns: []string{agent.AuditRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditrecord.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuditRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.AuditRecordsTable,
			Columns: []string{agent.AuditRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditrecord.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FeatureCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.FeatureTable,
			Columns: []string{agent.FeatureColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(feature.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFeatureIDs(); len(nodes) > 0 && !_u.mutation.FeatureCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.FeatureTable,
			Columns: []string{agent.FeatureColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(feature.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FeatureIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.FeatureTable,
			Columns: []string{agent.FeatureColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(feature.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Agent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
