// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"go-backend-template/ent/auditrecord"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// AuditRecord is the model entity for the AuditRecord schema.
type AuditRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID string `json:"project_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// Prompt holds the value of the "prompt" field.
	Prompt string `json:"prompt,omitempty"`
	// ProposedAction holds the value of the "proposed_action" field.
	ProposedAction map[string]interface{} `json:"proposed_action,omitempty"`
	// Validated holds the value of the "validated" field.
	Validated bool `json:"validated,omitempty"`
	// FinalResponse holds the value of the "final_response" field.
	FinalResponse map[string]interface{} `json:"final_response,omitempty"`
	selectValues  sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AuditRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case auditrecord.FieldProposedAction, auditrecord.FieldFinalResponse:
			values[i] = new([]byte)
		case auditrecord.FieldValidated:
			values[i] = new(sql.NullBool)
		case auditrecord.FieldID:
			values[i] = new(sql.NullInt64)
		case auditrecord.FieldProjectID, auditrecord.FieldUserID, auditrecord.FieldPrompt:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AuditRecord fields.
func (_m *AuditRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case auditrecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case auditrecord.FieldProjectID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value.Valid {
				_m.ProjectID = value.String
			}
		case auditrecord.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		case auditrecord.FieldPrompt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt", values[i])
			} else if value.Valid {
				_m.Prompt = value.String
			}
		case auditrecord.FieldProposedAction:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field proposed_action", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ProposedAction); err != nil {
					return fmt.Errorf("unmarshal field proposed_action: %w", err)
				}
			}
		case auditrecord.FieldValidated:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field validated", values[i])
			} else if value.Valid {
				_m.Validated = value.Bool
			}
		case auditrecord.FieldFinalResponse:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field final_response", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.FinalResponse); err != nil {
					return fmt.Errorf("unmarshal field final_response: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AuditRecord.
// This includes values selected through modifiers, order, etc.
func (_m *AuditRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AuditRecord.
// Note that you need to call AuditRecord.Unwrap() before calling this method if this AuditRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AuditRecord) Update() *AuditRecordUpdateOne {
	return NewAuditRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AuditRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AuditRecord) Unwrap() *AuditRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AuditRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AuditRecord) String() string {
	var builder strings.Builder
	builder.WriteString("AuditRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("project_id=")
	builder.WriteString(_m.ProjectID)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteString(", ")
	builder.WriteString("prompt=")
	builder.WriteString(_m.Prompt)
	builder.WriteString(", ")
	builder.WriteString("proposed_action=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProposedAction))
	builder.WriteString(", ")
	builder.WriteString("validated=")
	builder.WriteString(fmt.Sprintf("%v", _m.Validated))
	builder.WriteString(", ")
	builder.WriteString("final_response=")
	builder.WriteString(fmt.Sprintf("%v", _m.FinalResponse))
	builder.WriteByte(')')
	return builder.String()
}

// AuditRecords is a parsable slice of AuditRecord.
type AuditRecords []*AuditRecord
