// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/Emmanuel-Soempit/axiom/ent/auditrecord"
	"github.com/Emmanuel-Soempit/axiom/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuditRecordDelete is the builder for deleting a AuditRecord entity.
type AuditRecordDelete struct {
	config
	hooks    []Hook
	mutation *AuditRecordMutation
}

// Where appends a list predicates to the AuditRecordDelete builder.
func (_d *AuditRecordDelete) Where(ps ...predicate.AuditRecord) *AuditRecordDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AuditRecordDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AuditRecordDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AuditRecordDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(auditrecord.Table, sqlgraph.NewFieldSpec(auditrecord.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AuditRecordDeleteOne is the builder for deleting a single AuditRecord entity.
type AuditRecordDeleteOne struct {
	_d *AuditRecordDelete
}

// Where appends a list predicates to the AuditRecordDelete builder.
func (_d *AuditRecordDeleteOne) Where(ps ...predicate.AuditRecord) *AuditRecordDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AuditRecordDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{auditrecord.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AuditRecordDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
