// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-backend-template/ent/auditrecord"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuditRecordCreate is the builder for creating a AuditRecord entity.
type AuditRecordCreate struct {
	config
	mutation *AuditRecordMutation
	hooks    []Hook
}

// SetProjectID sets the "project_id" field.
func (_c *AuditRecordCreate) SetProjectID(v string) *AuditRecordCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *AuditRecordCreate) SetUserID(v string) *AuditRecordCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetPrompt sets the "prompt" field.
func (_c *AuditRecordCreate) SetPrompt(v string) *AuditRecordCreate {
	_c.mutation.SetPrompt(v)
	return _c
}

// SetProposedAction sets the "proposed_action" field.
func (_c *AuditRecordCreate) SetProposedAction(v map[string]interface{}) *AuditRecordCreate {
	_c.mutation.SetProposedAction(v)
	return _c
}

// SetValidated sets the "validated" field.
func (_c *AuditRecordCreate) SetValidated(v bool) *AuditRecordCreate {
	_c.mutation.SetValidated(v)
	return _c
}

// SetNillableValidated sets the "validated" field if the given value is not nil.
func (_c *AuditRecordCreate) SetNillableValidated(v *bool) *AuditRecordCreate {
	if v != nil {
		_c.SetValidated(*v)
	}
	return _c
}

// SetFinalResponse sets the "final_response" field.
func (_c *AuditRecordCreate) SetFinalResponse(v map[string]interface{}) *AuditRecordCreate {
	_c.mutation.SetFinalResponse(v)
	return _c
}

// Mutation returns the AuditRecordMutation object of the builder.
func (_c *AuditRecordCreate) Mutation() *AuditRecordMutation {
	return _c.mutation
}

// Save creates the AuditRecord in the database.
func (_c *AuditRecordCreate) Save(ctx context.Context) (*AuditRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuditRecordCreate) SaveX(ctx context.Context) *AuditRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuditRecordCreate) defaults() {
	if _, ok := _c.mutation.Validated(); !ok {
		v := auditrecord.DefaultValidated
		_c.mutation.SetValidated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuditRecordCreate) check() error {
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "AuditRecord.project_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "AuditRecord.user_id"`)}
	}
	if _, ok := _c.mutation.Prompt(); !ok {
		return &ValidationError{Name: "prompt", err: errors.New(`ent: missing required field "AuditRecord.prompt"`)}
	}
	if _, ok := _c.mutation.Validated(); !ok {
		return &ValidationError{Name: "validated", err: errors.New(`ent: missing required field "AuditRecord.validated"`)}
	}
	return nil
}

func (_c *AuditRecordCreate) sqlSave(ctx context.Context) (*AuditRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuditRecordCreate) createSpec() (*AuditRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &AuditRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(auditrecord.Table, sqlgraph.NewFieldSpec(auditrecord.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ProjectID(); ok {
		_spec.SetField(auditrecord.FieldProjectID, field.TypeString, value)
		_node.ProjectID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(auditrecord.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Prompt(); ok {
		_spec.SetField(auditrecord.FieldPrompt, field.TypeString, value)
		_node.Prompt = value
	}
	if value, ok := _c.mutation.ProposedAction(); ok {
		_spec.SetField(auditrecord.FieldProposedAction, field.TypeJSON, value)
		_node.ProposedAction = value
	}
	if value, ok := _c.mutation.Validated(); ok {
		_spec.SetField(auditrecord.FieldValidated, field.TypeBool, value)
		_node.Validated = value
	}
	if value, ok := _c.mutation.FinalResponse(); ok {
		_spec.SetField(auditrecord.FieldFinalResponse, field.TypeJSON, value)
		_node.FinalResponse = value
	}
	return _node, _spec
}

// AuditRecordCreateBulk is the builder for creating many AuditRecord entities in bulk.
type AuditRecordCreateBulk struct {
	config
	err      error
	builders []*AuditRecordCreate
}

// Save creates the AuditRecord entities in the database.
func (_c *AuditRecordCreateBulk) Save(ctx context.Context) ([]*AuditRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuditRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuditRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuditRecordCreateBulk) SaveX(ctx context.Context) []*AuditRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
