// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-backend-template/ent/auditrecord"
	"go-backend-template/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuditRecordUpdate is the builder for updating AuditRecord entities.
type AuditRecordUpdate struct {
	config
	hooks    []Hook
	mutation *AuditRecordMutation
}

// Where appends a list predicates to the AuditRecordUpdate builder.
func (_u *AuditRecordUpdate) Where(ps ...predicate.AuditRecord) *AuditRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *AuditRecordUpdate) SetProjectID(v string) *AuditRecordUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *AuditRecordUpdate) SetNillableProjectID(v *string) *AuditRecordUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AuditRecordUpdate) SetUserID(v string) *AuditRecordUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AuditRecordUpdate) SetNillableUserID(v *string) *AuditRecordUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPrompt sets the "prompt" field.
func (_u *AuditRecordUpdate) SetPrompt(v string) *AuditRecordUpdate {
	_u.mutation.SetPrompt(v)
	return _u
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_u *AuditRecordUpdate) SetNillablePrompt(v *string) *AuditRecordUpdate {
	if v != nil {
		_u.SetPrompt(*v)
	}
	return _u
}

// SetProposedAction sets the "proposed_action" field.
func (_u *AuditRecordUpdate) SetProposedAction(v map[string]interface{}) *AuditRecordUpdate {
	_u.mutation.SetProposedAction(v)
	return _u
}

// ClearProposedAction clears the value of the "proposed_action" field.
func (_u *AuditRecordUpdate) ClearProposedAction() *AuditRecordUpdate {
	_u.mutation.ClearProposedAction()
	return _u
}

// SetValidated sets the "validated" field.
func (_u *AuditRecordUpdate) SetValidated(v bool) *AuditRecordUpdate {
	_u.mutation.SetValidated(v)
	return _u
}

// SetNillableValidated sets the "validated" field if the given value is not nil.
func (_u *AuditRecordUpdate) SetNillableValidated(v *bool) *AuditRecordUpdate {
	if v != nil {
		_u.SetValidated(*v)
	}
	return _u
}

// SetFinalResponse sets the "final_response" field.
func (_u *AuditRecordUpdate) SetFinalResponse(v map[string]interface{}) *AuditRecordUpdate {
	_u.mutation.SetFinalResponse(v)
	return _u
}

// ClearFinalResponse clears the value of the "final_response" field.
func (_u *AuditRecordUpdate) ClearFinalResponse() *AuditRecordUpdate {
	_u.mutation.ClearFinalResponse()
	return _u
}

// Mutation returns the AuditRecordMutation object of the builder.
func (_u *AuditRecordUpdate) Mutation() *AuditRecordMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuditRecordUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuditRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AuditRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(auditrecord.Table, auditrecord.Columns, sqlgraph.NewFieldSpec(auditrecord.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(auditrecord.FieldProjectID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(auditrecord.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Prompt(); ok {
		_spec.SetField(auditrecord.FieldPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProposedAction(); ok {
		_spec.SetField(auditrecord.FieldProposedAction, field.TypeJSON, value)
	}
	if _u.mutation.ProposedActionCleared() {
		_spec.ClearField(auditrecord.FieldProposedAction, field.TypeJSON)
	}
	if value, ok := _u.mutation.Validated(); ok {
		_spec.SetField(auditrecord.FieldValidated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FinalResponse(); ok {
		_spec.SetField(auditrecord.FieldFinalResponse, field.TypeJSON, value)
	}
	if _u.mutation.FinalResponseCleared() {
		_spec.ClearField(auditrecord.FieldFinalResponse, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuditRecordUpdateOne is the builder for updating a single AuditRecord entity.
type AuditRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuditRecordMutation
}

// SetProjectID sets the "project_id" field.
func (_u *AuditRecordUpdateOne) SetProjectID(v string) *AuditRecordUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *AuditRecordUpdateOne) SetNillableProjectID(v *string) *AuditRecordUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AuditRecordUpdateOne) SetUserID(v string) *AuditRecordUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AuditRecordUpdateOne) SetNillableUserID(v *string) *AuditRecordUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPrompt sets the "prompt" field.
func (_u *AuditRecordUpdateOne) SetPrompt(v string) *AuditRecordUpdateOne {
	_u.mutation.SetPrompt(v)
	return _u
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_u *AuditRecordUpdateOne) SetNillablePrompt(v *string) *AuditRecordUpdateOne {
	if v != nil {
		_u.SetPrompt(*v)
	}
	return _u
}

// SetProposedAction sets the "proposed_action" field.
func (_u *AuditRecordUpdateOne) SetProposedAction(v map[string]interface{}) *AuditRecordUpdateOne {
	_u.mutation.SetProposedAction(v)
	return _u
}

// ClearProposedAction clears the value of the "proposed_action" field.
func (_u *AuditRecordUpdateOne) ClearProposedAction() *AuditRecordUpdateOne {
	_u.mutation.ClearProposedAction()
	return _u
}

// SetValidated sets the "validated" field.
func (_u *AuditRecordUpdateOne) SetValidated(v bool) *AuditRecordUpdateOne {
	_u.mutation.SetValidated(v)
	return _u
}

// SetNillableValidated sets the "validated" field if the given value is not nil.
func (_u *AuditRecordUpdateOne) SetNillableValidated(v *bool) *AuditRecordUpdateOne {
	if v != nil {
		_u.SetValidated(*v)
	}
	return _u
}

// SetFinalResponse sets the "final_response" field.
func (_u *AuditRecordUpdateOne) SetFinalResponse(v map[string]interface{}) *AuditRecordUpdateOne {
	_u.mutation.SetFinalResponse(v)
	return _u
}

// ClearFinalResponse clears the value of the "final_response" field.
func (_u *AuditRecordUpdateOne) ClearFinalResponse() *AuditRecordUpdateOne {
	_u.mutation.ClearFinalResponse()
	return _u
}

// Mutation returns the AuditRecordMutation object of the builder.
func (_u *AuditRecordUpdateOne) Mutation() *AuditRecordMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuditRecordUpdate builder.
func (_u *AuditRecordUpdateOne) Where(ps ...predicate.AuditRecord) *AuditRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuditRecordUpdateOne) Select(field string, fields ...string) *AuditRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuditRecord entity.
func (_u *AuditRecordUpdateOne) Save(ctx context.Context) (*AuditRecord, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditRecordUpdateOne) SaveX(ctx context.Context) *AuditRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuditRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AuditRecordUpdateOne) sqlSave(ctx context.Context) (_node *AuditRecord, err error) {
	_spec := sqlgraph.NewUpdateSpec(auditrecord.Table, auditrecord.Columns, sqlgraph.NewFieldSpec(auditrecord.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuditRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, auditrecord.FieldID)
		for _, f := range fields {
			if !auditrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != auditrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(auditrecord.FieldProjectID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(auditrecord.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Prompt(); ok {
		_spec.SetField(auditrecord.FieldPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProposedAction(); ok {
		_spec.SetField(auditrecord.FieldProposedAction, field.TypeJSON, value)
	}
	if _u.mutation.ProposedActionCleared() {
		_spec.ClearField(auditrecord.FieldProposedAction, field.TypeJSON)
	}
	if value, ok := _u.mutation.Validated(); ok {
		_spec.SetField(auditrecord.FieldValidated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FinalResponse(); ok {
		_spec.SetField(auditrecord.FieldFinalResponse, field.TypeJSON, value)
	}
	if _u.mutation.FinalResponseCleared() {
		_spec.ClearField(auditrecord.FieldFinalResponse, field.TypeJSON)
	}
	_node = &AuditRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
