// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-backend-template/ent/actionmodel"
	"go-backend-template/ent/message"
	"go-backend-template/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// MessageUpdate is the builder for updating Message entities.
type MessageUpdate struct {
	config
	hooks    []Hook
	mutation *MessageMutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (_u *MessageUpdate) Where(ps ...predicate.Message) *MessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MessageUpdate) SetUpdatedAt(v time.Time) *MessageUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *MessageUpdate) SetSessionID(v uuid.UUID) *MessageUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableSessionID(v *uuid.UUID) *MessageUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *MessageUpdate) SetRole(v message.Role) *MessageUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableRole(v *message.Role) *MessageUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *MessageUpdate) SetContent(v string) *MessageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableContent(v *string) *MessageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *MessageUpdate) ClearContent() *MessageUpdate {
	_u.mutation.ClearContent()
	return _u
}

// SetActionName sets the "action_name" field.
func (_u *MessageUpdate) SetActionName(v string) *MessageUpdate {
	_u.mutation.SetActionName(v)
	return _u
}

// SetNillableActionName sets the "action_name" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableActionName(v *string) *MessageUpdate {
	if v != nil {
		_u.SetActionName(*v)
	}
	return _u
}

// ClearActionName clears the value of the "action_name" field.
func (_u *MessageUpdate) ClearActionName() *MessageUpdate {
	_u.mutation.ClearActionName()
	return _u
}

// SetCallID sets the "call_id" field.
func (_u *MessageUpdate) SetCallID(v string) *MessageUpdate {
	_u.mutation.SetCallID(v)
	return _u
}

// SetNillableCallID sets the "call_id" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableCallID(v *string) *MessageUpdate {
	if v != nil {
		_u.SetCallID(*v)
	}
	return _u
}

// ClearCallID clears the value of the "call_id" field.
func (_u *MessageUpdate) ClearCallID() *MessageUpdate {
	_u.mutation.ClearCallID()
	return _u
}

// SetArguments sets the "arguments" field.
func (_u *MessageUpdate) SetArguments(v map[string]interface{}) *MessageUpdate {
	_u.mutation.SetArguments(v)
	return _u
}

// ClearArguments clears the value of the "arguments" field.
func (_u *MessageUpdate) ClearArguments() *MessageUpdate {
	_u.mutation.ClearArguments()
	return _u
}

// SetOpaDecision sets the "opa_decision" field.
func (_u *MessageUpdate) SetOpaDecision(v map[string]interface{}) *MessageUpdate {
	_u.mutation.SetOpaDecision(v)
	return _u
}

// ClearOpaDecision clears the value of the "opa_decision" field.
func (_u *MessageUpdate) ClearOpaDecision() *MessageUpdate {
	_u.mutation.ClearOpaDecision()
	return _u
}

// SetActionID sets the "action" edge to the ActionModel entity by ID.
func (_u *MessageUpdate) SetActionID(id int) *MessageUpdate {
	_u.mutation.SetActionID(id)
	return _u
}

// SetNillableActionID sets the "action" edge to the ActionModel entity by ID if the given value is not nil.
func (_u *MessageUpdate) SetNillableActionID(id *int) *MessageUpdate {
	if id != nil {
		_u = _u.SetActionID(*id)
	}
	return _u
}

// SetAction sets the "action" edge to the ActionModel entity.
func (_u *MessageUpdate) SetAction(v *ActionModel) *MessageUpdate {
	return _u.SetActionID(v.ID)
}

// Mutation returns the MessageMutation object of the builder.
func (_u *MessageUpdate) Mutation() *MessageMutation {
	return _u.mutation
}

// ClearAction clears the "action" edge to the ActionModel entity.
func (_u *MessageUpdate) ClearAction() *MessageUpdate {
	_u.mutation.ClearAction()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MessageUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MessageUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := message.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MessageUpdate) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := message.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Message.role": %w`, err)}
		}
	}
	return nil
}

func (_u *MessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(message.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(message.FieldSessionID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(message.FieldRole, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(message.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(message.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.ActionName(); ok {
		_spec.SetField(message.FieldActionName, field.TypeString, value)
	}
	if _u.mutation.ActionNameCleared() {
		_spec.ClearField(message.FieldActionName, field.TypeString)
	}
	if value, ok := _u.mutation.CallID(); ok {
		_spec.SetField(message.FieldCallID, field.TypeString, value)
	}
	if _u.mutation.CallIDCleared() {
		_spec.ClearField(message.FieldCallID, field.TypeString)
	}
	if value, ok := _u.mutation.Arguments(); ok {
		_spec.SetField(message.FieldArguments, field.TypeJSON, value)
	}
	if _u.mutation.ArgumentsCleared() {
		_spec.ClearField(message.FieldArguments, field.TypeJSON)
	}
	if value, ok := _u.mutation.OpaDecision(); ok {
		_spec.SetField(message.FieldOpaDecision, field.TypeJSON, value)
	}
	if _u.mutation.OpaDecisionCleared() {
		_spec.ClearField(message.FieldOpaDecision, field.TypeJSON)
	}
	if _u.mutation.ActionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.ActionTable,
			Columns: []string{message.ActionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actionmodel.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.ActionTable,
			Columns: []string{message.ActionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actionmodel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MessageUpdateOne is the builder for updating a single Message entity.
type MessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MessageUpdateOne) SetUpdatedAt(v time.Time) *MessageUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *MessageUpdateOne) SetSessionID(v uuid.UUID) *MessageUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableSessionID(v *uuid.UUID) *MessageUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *MessageUpdateOne) SetRole(v message.Role) *MessageUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableRole(v *message.Role) *MessageUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *MessageUpdateOne) SetContent(v string) *MessageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableContent(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *MessageUpdateOne) ClearContent() *MessageUpdateOne {
	_u.mutation.ClearContent()
	return _u
}

// SetActionName sets the "action_name" field.
func (_u *MessageUpdateOne) SetActionName(v string) *MessageUpdateOne {
	_u.mutation.SetActionName(v)
	return _u
}

// SetNillableActionName sets the "action_name" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableActionName(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetActionName(*v)
	}
	return _u
}

// ClearActionName clears the value of the "action_name" field.
func (_u *MessageUpdateOne) ClearActionName() *MessageUpdateOne {
	_u.mutation.ClearActionName()
	return _u
}

// SetCallID sets the "call_id" field.
func (_u *MessageUpdateOne) SetCallID(v string) *MessageUpdateOne {
	_u.mutation.SetCallID(v)
	return _u
}

// SetNillableCallID sets the "call_id" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableCallID(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetCallID(*v)
	}
	return _u
}

// ClearCallID clears the value of the "call_id" field.
func (_u *MessageUpdateOne) ClearCallID() *MessageUpdateOne {
	_u.mutation.ClearCallID()
	return _u
}

// SetArguments sets the "arguments" field.
func (_u *MessageUpdateOne) SetArguments(v map[string]interface{}) *MessageUpdateOne {
	_u.mutation.SetArguments(v)
	return _u
}

// ClearArguments clears the value of the "arguments" field.
func (_u *MessageUpdateOne) ClearArguments() *MessageUpdateOne {
	_u.mutation.ClearArguments()
	return _u
}

// SetOpaDecision sets the "opa_decision" field.
func (_u *MessageUpdateOne) SetOpaDecision(v map[string]interface{}) *MessageUpdateOne {
	_u.mutation.SetOpaDecision(v)
	return _u
}

// ClearOpaDecision clears the value of the "opa_decision" field.
func (_u *MessageUpdateOne) ClearOpaDecision() *MessageUpdateOne {
	_u.mutation.ClearOpaDecision()
	return _u
}

// SetActionID sets the "action" edge to the ActionModel entity by ID.
func (_u *MessageUpdateOne) SetActionID(id int) *MessageUpdateOne {
	_u.mutation.SetActionID(id)
	return _u
}

// SetNillableActionID sets the "action" edge to the ActionModel entity by ID if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableActionID(id *int) *MessageUpdateOne {
	if id != nil {
		_u = _u.SetActionID(*id)
	}
	return _u
}

// SetAction sets the "action" edge to the ActionModel entity.
func (_u *MessageUpdateOne) SetAction(v *ActionModel) *MessageUpdateOne {
	return _u.SetActionID(v.ID)
}

// Mutation returns the MessageMutation object of the builder.
func (_u *MessageUpdateOne) Mutation() *MessageMutation {
	return _u.mutation
}

// ClearAction clears the "action" edge to the ActionModel entity.
func (_u *MessageUpdateOne) ClearAction() *MessageUpdateOne {
	_u.mutation.ClearAction()
	return _u
}

// Where appends a list predicates to the MessageUpdate builder.
func (_u *MessageUpdateOne) Where(ps ...predicate.Message) *MessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MessageUpdateOne) Select(field string, fields ...string) *MessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Message entity.
func (_u *MessageUpdateOne) Save(ctx context.Context) (*Message, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageUpdateOne) SaveX(ctx context.Context) *Message {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MessageUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := message.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MessageUpdateOne) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := message.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Message.role": %w`, err)}
		}
	}
	return nil
}

func (_u *MessageUpdateOne) sqlSave(ctx context.Context) (_node *Message, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Message.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, message.FieldID)
		for _, f := range fields {
			if !message.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != message.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(message.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(message.FieldSessionID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(message.FieldRole, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(message.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(message.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.ActionName(); ok {
		_spec.SetField(message.FieldActionName, field.TypeString, value)
	}
	if _u.mutation.ActionNameCleared() {
		_spec.ClearField(message.FieldActionName, field.TypeString)
	}
	if value, ok := _u.mutation.CallID(); ok {
		_spec.SetField(message.FieldCallID, field.TypeString, value)
	}
	if _u.mutation.CallIDCleared() {
		_spec.ClearField(message.FieldCallID, field.TypeString)
	}
	if value, ok := _u.mutation.Arguments(); ok {
		_spec.SetField(message.FieldArguments, field.TypeJSON, value)
	}
	if _u.mutation.ArgumentsCleared() {
		_spec.ClearField(message.FieldArguments, field.TypeJSON)
	}
	if value, ok := _u.mutation.OpaDecision(); ok {
		_spec.SetField(message.FieldOpaDecision, field.TypeJSON, value)
	}
	if _u.mutation.OpaDecisionCleared() {
		_spec.ClearField(message.FieldOpaDecision, field.TypeJSON)
	}
	if _u.mutation.ActionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.ActionTable,
			Columns: []string{message.ActionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actionmodel.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.ActionTable,
			Columns: []string{message.ActionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actionmodel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Message{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
