// Code generated by ent, DO NOT EDIT.

package ent

import (
	"go-backend-template/ent/actionmodel"
	"go-backend-template/ent/auditrecord"
	"go-backend-template/ent/schema"
	"go-backend-template/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	actionmodelFields := schema.ActionModel{}.Fields()
	_ = actionmodelFields
	// actionmodelDescVersion is the schema descriptor for version field.
	actionmodelDescVersion := actionmodelFields[6].Descriptor()
	// actionmodel.DefaultVersion holds the default value on creation for the version field.
	actionmodel.DefaultVersion = actionmodelDescVersion.Default.(int)
	auditrecordFields := schema.AuditRecord{}.Fields()
	_ = auditrecordFields
	// auditrecordDescValidated is the schema descriptor for validated field.
	auditrecordDescValidated := auditrecordFields[4].Descriptor()
	// auditrecord.DefaultValidated holds the default value on creation for the validated field.
	auditrecord.DefaultValidated = auditrecordDescValidated.Default.(bool)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescFirstname is the schema descriptor for firstname field.
	userDescFirstname := userFields[0].Descriptor()
	// user.FirstnameValidator is a validator for the "firstname" field. It is called by the builders before save.
	user.FirstnameValidator = userDescFirstname.Validators[0].(func(string) error)
	// userDescLastname is the schema descriptor for lastname field.
	userDescLastname := userFields[1].Descriptor()
	// user.LastnameValidator is a validator for the "lastname" field. It is called by the builders before save.
	user.LastnameValidator = userDescLastname.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
}
