// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"github.com/Emmanuel-Soempit/axiom/ent/project"
	"github.com/Emmanuel-Soempit/axiom/ent/user"
	"github.com/Emmanuel-Soempit/axiom/ent/usermeta"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// UserMeta is the model entity for the UserMeta schema.
type UserMeta struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// LastLoggedIn holds the value of the "last_logged_in" field.
	LastLoggedIn *time.Time `json:"last_logged_in,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// LastActiveProject holds the value of the "last_active_project" field.
	LastActiveProject *string `json:"last_active_project,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserMetaQuery when eager-loading is set.
	Edges        UserMetaEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserMetaEdges holds the relations/edges for other nodes in the graph.
type UserMetaEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserMetaEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserMetaEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserMeta) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usermeta.FieldID, usermeta.FieldUserID:
			values[i] = new(sql.NullInt64)
		case usermeta.FieldLastActiveProject:
			values[i] = new(sql.NullString)
		case usermeta.FieldCreatedAt, usermeta.FieldUpdatedAt, usermeta.FieldLastLoggedIn:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserMeta fields.
func (_m *UserMeta) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usermeta.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case usermeta.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case usermeta.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case usermeta.FieldLastLoggedIn:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_logged_in", values[i])
			} else if value.Valid {
				_m.LastLoggedIn = new(time.Time)
				*_m.LastLoggedIn = value.Time
			}
		case usermeta.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case usermeta.FieldLastActiveProject:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_active_project", values[i])
			} else if value.Valid {
				_m.LastActiveProject = new(string)
				*_m.LastActiveProject = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserMeta.
// This includes values selected through modifiers, order, etc.
func (_m *UserMeta) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserMeta entity.
func (_m *UserMeta) QueryUser() *UserQuery {
	return NewUserMetaClient(_m.config).QueryUser(_m)
}

// QueryProject queries the "project" edge of the UserMeta entity.
func (_m *UserMeta) QueryProject() *ProjectQuery {
	return NewUserMetaClient(_m.config).QueryProject(_m)
}

// Update returns a builder for updating this UserMeta.
// Note that you need to call UserMeta.Unwrap() before calling this method if this UserMeta
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserMeta) Update() *UserMetaUpdateOne {
	return NewUserMetaClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserMeta entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserMeta) Unwrap() *UserMeta {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserMeta is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserMeta) String() string {
	var builder strings.Builder
	builder.WriteString("UserMeta(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.LastLoggedIn; v != nil {
		builder.WriteString("last_logged_in=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	if v := _m.LastActiveProject; v != nil {
		builder.WriteString("last_active_project=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// UserMetaSlice is a parsable slice of UserMeta.
type UserMetaSlice []*UserMeta
