// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"github.com/Emmanuel-Soempit/axiom/ent/user"
	"github.com/Emmanuel-Soempit/axiom/ent/userinvitation"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// UserInvitation is the model entity for the UserInvitation schema.
type UserInvitation struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// InviteURL holds the value of the "invite_url" field.
	InviteURL string `json:"invite_url,omitempty"`
	// Status holds the value of the "status" field.
	Status userinvitation.Status `json:"status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserInvitationQuery when eager-loading is set.
	Edges            UserInvitationEdges `json:"edges"`
	user_invitations *int
	selectValues     sql.SelectValues
}

// UserInvitationEdges holds the relations/edges for other nodes in the graph.
type UserInvitationEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserInvitationEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserInvitation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userinvitation.FieldID:
			values[i] = new(sql.NullInt64)
		case userinvitation.FieldInviteURL, userinvitation.FieldStatus:
			values[i] = new(sql.NullString)
		case userinvitation.FieldCreatedAt, userinvitation.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case userinvitation.ForeignKeys[0]: // user_invitations
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserInvitation fields.
func (_m *UserInvitation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userinvitation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case userinvitation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case userinvitation.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case userinvitation.FieldInviteURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field invite_url", values[i])
			} else if value.Valid {
				_m.InviteURL = value.String
			}
		case userinvitation.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = userinvitation.Status(value.String)
			}
		case userinvitation.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_invitations", value)
			} else if value.Valid {
				_m.user_invitations = new(int)
				*_m.user_invitations = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserInvitation.
// This includes values selected through modifiers, order, etc.
func (_m *UserInvitation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserInvitation entity.
func (_m *UserInvitation) QueryUser() *UserQuery {
	return NewUserInvitationClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this UserInvitation.
// Note that you need to call UserInvitation.Unwrap() before calling this method if this UserInvitation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserInvitation) Update() *UserInvitationUpdateOne {
	return NewUserInvitationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserInvitation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserInvitation) Unwrap() *UserInvitation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserInvitation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserInvitation) String() string {
	var builder strings.Builder
	builder.WriteString("UserInvitation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("invite_url=")
	builder.WriteString(_m.InviteURL)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteByte(')')
	return builder.String()
}

// UserInvitations is a parsable slice of UserInvitation.
type UserInvitations []*UserInvitation
