// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/Emmanuel-Soempit/axiom/ent/predicate"
	"github.com/Emmanuel-Soempit/axiom/ent/userinvitation"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserInvitationDelete is the builder for deleting a UserInvitation entity.
type UserInvitationDelete struct {
	config
	hooks    []Hook
	mutation *UserInvitationMutation
}

// Where appends a list predicates to the UserInvitationDelete builder.
func (_d *UserInvitationDelete) Where(ps ...predicate.UserInvitation) *UserInvitationDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UserInvitationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserInvitationDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UserInvitationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(userinvitation.Table, sqlgraph.NewFieldSpec(userinvitation.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UserInvitationDeleteOne is the builder for deleting a single UserInvitation entity.
type UserInvitationDeleteOne struct {
	_d *UserInvitationDelete
}

// Where appends a list predicates to the UserInvitationDelete builder.
func (_d *UserInvitationDeleteOne) Where(ps ...predicate.UserInvitation) *UserInvitationDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UserInvitationDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userinvitation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserInvitationDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
