// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-backend-template/ent/predicate"
	"go-backend-template/ent/project"
	"go-backend-template/ent/user"
	"go-backend-template/ent/usermeta"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserMetaUpdate is the builder for updating UserMeta entities.
type UserMetaUpdate struct {
	config
	hooks    []Hook
	mutation *UserMetaMutation
}

// Where appends a list predicates to the UserMetaUpdate builder.
func (_u *UserMetaUpdate) Where(ps ...predicate.UserMeta) *UserMetaUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserMetaUpdate) SetUpdatedAt(v time.Time) *UserMetaUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLastLoggedIn sets the "last_logged_in" field.
func (_u *UserMetaUpdate) SetLastLoggedIn(v time.Time) *UserMetaUpdate {
	_u.mutation.SetLastLoggedIn(v)
	return _u
}

// SetNillableLastLoggedIn sets the "last_logged_in" field if the given value is not nil.
func (_u *UserMetaUpdate) SetNillableLastLoggedIn(v *time.Time) *UserMetaUpdate {
	if v != nil {
		_u.SetLastLoggedIn(*v)
	}
	return _u
}

// ClearLastLoggedIn clears the value of the "last_logged_in" field.
func (_u *UserMetaUpdate) ClearLastLoggedIn() *UserMetaUpdate {
	_u.mutation.ClearLastLoggedIn()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserMetaUpdate) SetUserID(v int) *UserMetaUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserMetaUpdate) SetNillableUserID(v *int) *UserMetaUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetLastActiveProject sets the "last_active_project" field.
func (_u *UserMetaUpdate) SetLastActiveProject(v string) *UserMetaUpdate {
	_u.mutation.SetLastActiveProject(v)
	return _u
}

// SetNillableLastActiveProject sets the "last_active_project" field if the given value is not nil.
func (_u *UserMetaUpdate) SetNillableLastActiveProject(v *string) *UserMetaUpdate {
	if v != nil {
		_u.SetLastActiveProject(*v)
	}
	return _u
}

// ClearLastActiveProject clears the value of the "last_active_project" field.
func (_u *UserMetaUpdate) ClearLastActiveProject() *UserMetaUpdate {
	_u.mutation.ClearLastActiveProject()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserMetaUpdate) SetUser(v *User) *UserMetaUpdate {
	return _u.SetUserID(v.ID)
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_u *UserMetaUpdate) SetProjectID(id string) *UserMetaUpdate {
	_u.mutation.SetProjectID(id)
	return _u
}

// SetNillableProjectID sets the "project" edge to the Project entity by ID if the given value is not nil.
func (_u *UserMetaUpdate) SetNillableProjectID(id *string) *UserMetaUpdate {
	if id != nil {
		_u = _u.SetProjectID(*id)
	}
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *UserMetaUpdate) SetProject(v *Project) *UserMetaUpdate {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the UserMetaMutation object of the builder.
func (_u *UserMetaUpdate) Mutation() *UserMetaMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserMetaUpdate) ClearUser() *UserMetaUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *UserMetaUpdate) ClearProject() *UserMetaUpdate {
	_u.mutation.ClearProject()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserMetaUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserMetaUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserMetaUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserMetaUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserMetaUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usermeta.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserMetaUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserMeta.user"`)
	}
	return nil
}

func (_u *UserMetaUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usermeta.Table, usermeta.Columns, sqlgraph.NewFieldSpec(usermeta.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usermeta.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastLoggedIn(); ok {
		_spec.SetField(usermeta.FieldLastLoggedIn, field.TypeTime, value)
	}
	if _u.mutation.LastLoggedInCleared() {
		_spec.ClearField(usermeta.FieldLastLoggedIn, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   usermeta.UserTable,
			Columns: []string{usermeta.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   usermeta.UserTable,
			Columns: []string{usermeta.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usermeta.ProjectTable,
			Columns: []string{usermeta.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usermeta.ProjectTable,
			Columns: []string{usermeta.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usermeta.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserMetaUpdateOne is the builder for updating a single UserMeta entity.
type UserMetaUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMetaMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserMetaUpdateOne) SetUpdatedAt(v time.Time) *UserMetaUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLastLoggedIn sets the "last_logged_in" field.
func (_u *UserMetaUpdateOne) SetLastLoggedIn(v time.Time) *UserMetaUpdateOne {
	_u.mutation.SetLastLoggedIn(v)
	return _u
}

// SetNillableLastLoggedIn sets the "last_logged_in" field if the given value is not nil.
func (_u *UserMetaUpdateOne) SetNillableLastLoggedIn(v *time.Time) *UserMetaUpdateOne {
	if v != nil {
		_u.SetLastLoggedIn(*v)
	}
	return _u
}

// ClearLastLoggedIn clears the value of the "last_logged_in" field.
func (_u *UserMetaUpdateOne) ClearLastLoggedIn() *UserMetaUpdateOne {
	_u.mutation.ClearLastLoggedIn()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserMetaUpdateOne) SetUserID(v int) *UserMetaUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserMetaUpdateOne) SetNillableUserID(v *int) *UserMetaUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetLastActiveProject sets the "last_active_project" field.
func (_u *UserMetaUpdateOne) SetLastActiveProject(v string) *UserMetaUpdateOne {
	_u.mutation.SetLastActiveProject(v)
	return _u
}

// SetNillableLastActiveProject sets the "last_active_project" field if the given value is not nil.
func (_u *UserMetaUpdateOne) SetNillableLastActiveProject(v *string) *UserMetaUpdateOne {
	if v != nil {
		_u.SetLastActiveProject(*v)
	}
	return _u
}

// ClearLastActiveProject clears the value of the "last_active_project" field.
func (_u *UserMetaUpdateOne) ClearLastActiveProject() *UserMetaUpdateOne {
	_u.mutation.ClearLastActiveProject()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserMetaUpdateOne) SetUser(v *User) *UserMetaUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_u *UserMetaUpdateOne) SetProjectID(id string) *UserMetaUpdateOne {
	_u.mutation.SetProjectID(id)
	return _u
}

// SetNillableProjectID sets the "project" edge to the Project entity by ID if the given value is not nil.
func (_u *UserMetaUpdateOne) SetNillableProjectID(id *string) *UserMetaUpdateOne {
	if id != nil {
		_u = _u.SetProjectID(*id)
	}
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *UserMetaUpdateOne) SetProject(v *Project) *UserMetaUpdateOne {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the UserMetaMutation object of the builder.
func (_u *UserMetaUpdateOne) Mutation() *UserMetaMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserMetaUpdateOne) ClearUser() *UserMetaUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *UserMetaUpdateOne) ClearProject() *UserMetaUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// Where appends a list predicates to the UserMetaUpdate builder.
func (_u *UserMetaUpdateOne) Where(ps ...predicate.UserMeta) *UserMetaUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserMetaUpdateOne) Select(field string, fields ...string) *UserMetaUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserMeta entity.
func (_u *UserMetaUpdateOne) Save(ctx context.Context) (*UserMeta, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserMetaUpdateOne) SaveX(ctx context.Context) *UserMeta {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserMetaUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserMetaUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserMetaUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usermeta.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserMetaUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserMeta.user"`)
	}
	return nil
}

func (_u *UserMetaUpdateOne) sqlSave(ctx context.Context) (_node *UserMeta, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usermeta.Table, usermeta.Columns, sqlgraph.NewFieldSpec(usermeta.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserMeta.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usermeta.FieldID)
		for _, f := range fields {
			if !usermeta.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usermeta.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usermeta.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastLoggedIn(); ok {
		_spec.SetField(usermeta.FieldLastLoggedIn, field.TypeTime, value)
	}
	if _u.mutation.LastLoggedInCleared() {
		_spec.ClearField(usermeta.FieldLastLoggedIn, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   usermeta.UserTable,
			Columns: []string{usermeta.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   usermeta.UserTable,
			Columns: []string{usermeta.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usermeta.ProjectTable,
			Columns: []string{usermeta.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usermeta.ProjectTable,
			Columns: []string{usermeta.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserMeta{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usermeta.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
