// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"go-backend-template/ent/predicate"
	"go-backend-template/ent/usermeta"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserMetaDelete is the builder for deleting a UserMeta entity.
type UserMetaDelete struct {
	config
	hooks    []Hook
	mutation *UserMetaMutation
}

// Where appends a list predicates to the UserMetaDelete builder.
func (_d *UserMetaDelete) Where(ps ...predicate.UserMeta) *UserMetaDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UserMetaDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserMetaDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UserMetaDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(usermeta.Table, sqlgraph.NewFieldSpec(usermeta.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UserMetaDeleteOne is the builder for deleting a single UserMeta entity.
type UserMetaDeleteOne struct {
	_d *UserMetaDelete
}

// Where appends a list predicates to the UserMetaDelete builder.
func (_d *UserMetaDeleteOne) Where(ps ...predicate.UserMeta) *UserMetaDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UserMetaDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{usermeta.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserMetaDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
