apiVersion: v1
kind: ConfigMap
metadata:
  name: axiom-config
  namespace: axiom-dev
data:
  groq_api_url: "https://api.groq.com/openai/v1/chat/completions"
  frontend_url: "http://dev.axiom.soempit.com"
  port: "3333"

