// Code generated by ent, DO NOT EDIT.

package message

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the message type in the database.
	Label = "message"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldActionName holds the string denoting the action_name field in the database.
	FieldActionName = "action_name"
	// FieldCallID holds the string denoting the call_id field in the database.
	FieldCallID = "call_id"
	// FieldArguments holds the string denoting the arguments field in the database.
	FieldArguments = "arguments"
	// FieldOpaDecision holds the string denoting the opa_decision field in the database.
	FieldOpaDecision = "opa_decision"
	// EdgeAction holds the string denoting the action edge name in mutations.
	EdgeAction = "action"
	// Table holds the table name of the message in the database.
	Table = "messages"
	// ActionTable is the table that holds the action relation/edge.
	ActionTable = "messages"
	// ActionInverseTable is the table name for the ActionModel entity.
	// It exists in this package in order to avoid circular dependency with the "actionmodel" package.
	ActionInverseTable = "action_models"
	// ActionColumn is the table column denoting the action relation/edge.
	ActionColumn = "message_action"
)

// Columns holds all SQL columns for message fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldSessionID,
	FieldRole,
	FieldContent,
	FieldActionName,
	FieldCallID,
	FieldArguments,
	FieldOpaDecision,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "messages"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"message_action",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Role defines the type for the "role" enum field.
type Role string

// Role values.
const (
	RoleSystem       Role = "system"
	RoleUser         Role = "user"
	RoleAssistant    Role = "assistant"
	RoleActionResult Role = "action_result"
)

func (r Role) String() string {
	return string(r)
}

// RoleValidator is a validator for the "role" field enum values. It is called by the builders before save.
func RoleValidator(r Role) error {
	switch r {
	case RoleSystem, RoleUser, RoleAssistant, RoleActionResult:
		return nil
	default:
		return fmt.Errorf("message: invalid enum value for role field: %q", r)
	}
}

// OrderOption defines the ordering options for the Message queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByActionName orders the results by the action_name field.
func ByActionName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActionName, opts...).ToFunc()
}

// ByCallID orders the results by the call_id field.
func ByCallID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCallID, opts...).ToFunc()
}

// ByActionField orders the results by action field.
func ByActionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newActionStep(), sql.OrderByField(field, opts...))
	}
}
func newActionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ActionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ActionTable, ActionColumn),
	)
}
