apiVersion: v1
kind: ConfigMap
metadata:
  name: eac-config
  namespace: eac-staging
data:
  groq_api_url: "https://api.groq.com/openai/v1/chat/completions"
  frontend_url: "https://staging.eac.soempit.com"
