// Code generated by ent, DO NOT EDIT.

package actionmodel

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the actionmodel type in the database.
	Label = "action_model"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldParameters holds the string denoting the parameters field in the database.
	FieldParameters = "parameters"
	// FieldRules holds the string denoting the rules field in the database.
	FieldRules = "rules"
	// FieldRequiredFeature holds the string denoting the required_feature field in the database.
	FieldRequiredFeature = "required_feature"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// Table holds the table name of the actionmodel in the database.
	Table = "action_models"
)

// Columns holds all SQL columns for actionmodel fields.
var Columns = []string{
	FieldID,
	FieldProjectID,
	FieldName,
	FieldDescription,
	FieldParameters,
	FieldRules,
	FieldRequiredFeature,
	FieldVersion,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion int
)

// OrderOption defines the ordering options for the ActionModel queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByRequiredFeature orders the results by the required_feature field.
func ByRequiredFeature(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequiredFeature, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}
