// Code generated by ent, DO NOT EDIT.

package actionmodel

import (
	"go-backend-template/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldLTE(FieldID, id))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldEQ(FieldProjectID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldEQ(FieldDescription, v))
}

// RequiredFeature applies equality check predicate on the "required_feature" field. It's identical to RequiredFeatureEQ.
func RequiredFeature(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldEQ(FieldRequiredFeature, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldEQ(FieldVersion, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldNotIn(FieldProjectID, vs...))
}

// ProjectIDGT applies the GT predicate on the "project_id" field.
func ProjectIDGT(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldGT(FieldProjectID, v))
}

// ProjectIDGTE applies the GTE predicate on the "project_id" field.
func ProjectIDGTE(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldGTE(FieldProjectID, v))
}

// ProjectIDLT applies the LT predicate on the "project_id" field.
func ProjectIDLT(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldLT(FieldProjectID, v))
}

// ProjectIDLTE applies the LTE predicate on the "project_id" field.
func ProjectIDLTE(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldLTE(FieldProjectID, v))
}

// ProjectIDContains applies the Contains predicate on the "project_id" field.
func ProjectIDContains(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldContains(FieldProjectID, v))
}

// ProjectIDHasPrefix applies the HasPrefix predicate on the "project_id" field.
func ProjectIDHasPrefix(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldHasPrefix(FieldProjectID, v))
}

// ProjectIDHasSuffix applies the HasSuffix predicate on the "project_id" field.
func ProjectIDHasSuffix(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldHasSuffix(FieldProjectID, v))
}

// ProjectIDEqualFold applies the EqualFold predicate on the "project_id" field.
func ProjectIDEqualFold(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldEqualFold(FieldProjectID, v))
}

// ProjectIDContainsFold applies the ContainsFold predicate on the "project_id" field.
func ProjectIDContainsFold(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldContainsFold(FieldProjectID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldContainsFold(FieldDescription, v))
}

// RequiredFeatureEQ applies the EQ predicate on the "required_feature" field.
func RequiredFeatureEQ(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldEQ(FieldRequiredFeature, v))
}

// RequiredFeatureNEQ applies the NEQ predicate on the "required_feature" field.
func RequiredFeatureNEQ(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldNEQ(FieldRequiredFeature, v))
}

// RequiredFeatureIn applies the In predicate on the "required_feature" field.
func RequiredFeatureIn(vs ...string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldIn(FieldRequiredFeature, vs...))
}

// RequiredFeatureNotIn applies the NotIn predicate on the "required_feature" field.
func RequiredFeatureNotIn(vs ...string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldNotIn(FieldRequiredFeature, vs...))
}

// RequiredFeatureGT applies the GT predicate on the "required_feature" field.
func RequiredFeatureGT(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldGT(FieldRequiredFeature, v))
}

// RequiredFeatureGTE applies the GTE predicate on the "required_feature" field.
func RequiredFeatureGTE(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldGTE(FieldRequiredFeature, v))
}

// RequiredFeatureLT applies the LT predicate on the "required_feature" field.
func RequiredFeatureLT(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldLT(FieldRequiredFeature, v))
}

// RequiredFeatureLTE applies the LTE predicate on the "required_feature" field.
func RequiredFeatureLTE(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldLTE(FieldRequiredFeature, v))
}

// RequiredFeatureContains applies the Contains predicate on the "required_feature" field.
func RequiredFeatureContains(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldContains(FieldRequiredFeature, v))
}

// RequiredFeatureHasPrefix applies the HasPrefix predicate on the "required_feature" field.
func RequiredFeatureHasPrefix(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldHasPrefix(FieldRequiredFeature, v))
}

// RequiredFeatureHasSuffix applies the HasSuffix predicate on the "required_feature" field.
func RequiredFeatureHasSuffix(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldHasSuffix(FieldRequiredFeature, v))
}

// RequiredFeatureIsNil applies the IsNil predicate on the "required_feature" field.
func RequiredFeatureIsNil() predicate.ActionModel {
	return predicate.ActionModel(sql.FieldIsNull(FieldRequiredFeature))
}

// RequiredFeatureNotNil applies the NotNil predicate on the "required_feature" field.
func RequiredFeatureNotNil() predicate.ActionModel {
	return predicate.ActionModel(sql.FieldNotNull(FieldRequiredFeature))
}

// RequiredFeatureEqualFold applies the EqualFold predicate on the "required_feature" field.
func RequiredFeatureEqualFold(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldEqualFold(FieldRequiredFeature, v))
}

// RequiredFeatureContainsFold applies the ContainsFold predicate on the "required_feature" field.
func RequiredFeatureContainsFold(v string) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldContainsFold(FieldRequiredFeature, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int) predicate.ActionModel {
	return predicate.ActionModel(sql.FieldLTE(FieldVersion, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ActionModel) predicate.ActionModel {
	return predicate.ActionModel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ActionModel) predicate.ActionModel {
	return predicate.ActionModel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ActionModel) predicate.ActionModel {
	return predicate.ActionModel(sql.NotPredicates(p))
}
