apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: axiom-ingress
  namespace: axiom-prod
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - soempit.com
    - portal.soempit.com
    - api.soempit.com
    secretName: axiom-prod-tls
  rules:
  - host: soempit.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: axiom-frontend
            port:
              number: 3000
  - host: portal.soempit.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: axiom-web-app
            port:
              number: 3001
  - host: api.soempit.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: axiom-backend
            port:
              number: 3333
