apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namespace: axiom-dev

replicas:
- name: axiom-backend
  count: 1
- name: axiom-web-app
  count: 1
- name: axiom-frontend
  count: 1
- name: axiom-postgres
  count: 1

images:
- name: ghcr.io/emmanuel-soempit/axiom-backend
  newTag: develop
- name: ghcr.io/emmanuel-soempit/axiom-web-app
  newTag: develop
- name: ghcr.io/emmanuel-soempit/axiom-frontend
  newTag: develop

resources:
- secrets/sealed-secrets.yaml
- secrets/configmap.yaml
- ingress.yaml
