// Code generated by ent, DO NOT EDIT.

package auditrecord

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the auditrecord type in the database.
	Label = "audit_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldPrompt holds the string denoting the prompt field in the database.
	FieldPrompt = "prompt"
	// FieldProposedAction holds the string denoting the proposed_action field in the database.
	FieldProposedAction = "proposed_action"
	// FieldValidated holds the string denoting the validated field in the database.
	FieldValidated = "validated"
	// FieldFinalResponse holds the string denoting the final_response field in the database.
	FieldFinalResponse = "final_response"
	// Table holds the table name of the auditrecord in the database.
	Table = "audit_records"
)

// Columns holds all SQL columns for auditrecord fields.
var Columns = []string{
	FieldID,
	FieldProjectID,
	FieldUserID,
	FieldPrompt,
	FieldProposedAction,
	FieldValidated,
	FieldFinalResponse,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultValidated holds the default value on creation for the "validated" field.
	DefaultValidated bool
)

// OrderOption defines the ordering options for the AuditRecord queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByPrompt orders the results by the prompt field.
func ByPrompt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrompt, opts...).ToFunc()
}

// ByValidated orders the results by the validated field.
func ByValidated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValidated, opts...).ToFunc()
}
