// Code generated by ent, DO NOT EDIT.

package auditrecord

import (
	"time"

	"github.com/Emmanuel-Soempit/axiom/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldEQ(FieldUserID, v))
}

// ActionID applies equality check predicate on the "action_id" field. It's identical to ActionIDEQ.
func ActionID(v int) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldEQ(FieldActionID, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldEQ(FieldProjectID, v))
}

// Prompt applies equality check predicate on the "prompt" field. It's identical to PromptEQ.
func Prompt(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldEQ(FieldPrompt, v))
}

// Validated applies equality check predicate on the "validated" field. It's identical to ValidatedEQ.
func Validated(v bool) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldEQ(FieldValidated, v))
}

// AgentID applies equality check predicate on the "agent_id" field. It's identical to AgentIDEQ.
func AgentID(v int) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldEQ(FieldAgentID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNotNull(FieldUserID))
}

// ActionIDEQ applies the EQ predicate on the "action_id" field.
func ActionIDEQ(v int) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldEQ(FieldActionID, v))
}

// ActionIDNEQ applies the NEQ predicate on the "action_id" field.
func ActionIDNEQ(v int) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNEQ(FieldActionID, v))
}

// ActionIDIn applies the In predicate on the "action_id" field.
func ActionIDIn(vs ...int) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldIn(FieldActionID, vs...))
}

// ActionIDNotIn applies the NotIn predicate on the "action_id" field.
func ActionIDNotIn(vs ...int) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNotIn(FieldActionID, vs...))
}

// ActionIDIsNil applies the IsNil predicate on the "action_id" field.
func ActionIDIsNil() predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldIsNull(FieldActionID))
}

// ActionIDNotNil applies the NotNil predicate on the "action_id" field.
func ActionIDNotNil() predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNotNull(FieldActionID))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNotIn(FieldProjectID, vs...))
}

// ProjectIDGT applies the GT predicate on the "project_id" field.
func ProjectIDGT(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldGT(FieldProjectID, v))
}

// ProjectIDGTE applies the GTE predicate on the "project_id" field.
func ProjectIDGTE(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldGTE(FieldProjectID, v))
}

// ProjectIDLT applies the LT predicate on the "project_id" field.
func ProjectIDLT(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldLT(FieldProjectID, v))
}

// ProjectIDLTE applies the LTE predicate on the "project_id" field.
func ProjectIDLTE(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldLTE(FieldProjectID, v))
}

// ProjectIDContains applies the Contains predicate on the "project_id" field.
func ProjectIDContains(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldContains(FieldProjectID, v))
}

// ProjectIDHasPrefix applies the HasPrefix predicate on the "project_id" field.
func ProjectIDHasPrefix(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldHasPrefix(FieldProjectID, v))
}

// ProjectIDHasSuffix applies the HasSuffix predicate on the "project_id" field.
func ProjectIDHasSuffix(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldHasSuffix(FieldProjectID, v))
}

// ProjectIDIsNil applies the IsNil predicate on the "project_id" field.
func ProjectIDIsNil() predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldIsNull(FieldProjectID))
}

// ProjectIDNotNil applies the NotNil predicate on the "project_id" field.
func ProjectIDNotNil() predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNotNull(FieldProjectID))
}

// ProjectIDEqualFold applies the EqualFold predicate on the "project_id" field.
func ProjectIDEqualFold(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldEqualFold(FieldProjectID, v))
}

// ProjectIDContainsFold applies the ContainsFold predicate on the "project_id" field.
func ProjectIDContainsFold(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldContainsFold(FieldProjectID, v))
}

// PromptEQ applies the EQ predicate on the "prompt" field.
func PromptEQ(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldEQ(FieldPrompt, v))
}

// PromptNEQ applies the NEQ predicate on the "prompt" field.
func PromptNEQ(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNEQ(FieldPrompt, v))
}

// PromptIn applies the In predicate on the "prompt" field.
func PromptIn(vs ...string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldIn(FieldPrompt, vs...))
}

// PromptNotIn applies the NotIn predicate on the "prompt" field.
func PromptNotIn(vs ...string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNotIn(FieldPrompt, vs...))
}

// PromptGT applies the GT predicate on the "prompt" field.
func PromptGT(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldGT(FieldPrompt, v))
}

// PromptGTE applies the GTE predicate on the "prompt" field.
func PromptGTE(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldGTE(FieldPrompt, v))
}

// PromptLT applies the LT predicate on the "prompt" field.
func PromptLT(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldLT(FieldPrompt, v))
}

// PromptLTE applies the LTE predicate on the "prompt" field.
func PromptLTE(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldLTE(FieldPrompt, v))
}

// PromptContains applies the Contains predicate on the "prompt" field.
func PromptContains(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldContains(FieldPrompt, v))
}

// PromptHasPrefix applies the HasPrefix predicate on the "prompt" field.
func PromptHasPrefix(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldHasPrefix(FieldPrompt, v))
}

// PromptHasSuffix applies the HasSuffix predicate on the "prompt" field.
func PromptHasSuffix(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldHasSuffix(FieldPrompt, v))
}

// PromptEqualFold applies the EqualFold predicate on the "prompt" field.
func PromptEqualFold(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldEqualFold(FieldPrompt, v))
}

// PromptContainsFold applies the ContainsFold predicate on the "prompt" field.
func PromptContainsFold(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldContainsFold(FieldPrompt, v))
}

// ProposedActionIsNil applies the IsNil predicate on the "proposed_action" field.
func ProposedActionIsNil() predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldIsNull(FieldProposedAction))
}

// ProposedActionNotNil applies the NotNil predicate on the "proposed_action" field.
func ProposedActionNotNil() predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNotNull(FieldProposedAction))
}

// ValidatedEQ applies the EQ predicate on the "validated" field.
func ValidatedEQ(v bool) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldEQ(FieldValidated, v))
}

// ValidatedNEQ applies the NEQ predicate on the "validated" field.
func ValidatedNEQ(v bool) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNEQ(FieldValidated, v))
}

// ValidationErrorsIsNil applies the IsNil predicate on the "validation_errors" field.
func ValidationErrorsIsNil() predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldIsNull(FieldValidationErrors))
}

// ValidationErrorsNotNil applies the NotNil predicate on the "validation_errors" field.
func ValidationErrorsNotNil() predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNotNull(FieldValidationErrors))
}

// FinalResponseIsNil applies the IsNil predicate on the "final_response" field.
func FinalResponseIsNil() predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldIsNull(FieldFinalResponse))
}

// FinalResponseNotNil applies the NotNil predicate on the "final_response" field.
func FinalResponseNotNil() predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNotNull(FieldFinalResponse))
}

// AgentIDEQ applies the EQ predicate on the "agent_id" field.
func AgentIDEQ(v int) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldEQ(FieldAgentID, v))
}

// AgentIDNEQ applies the NEQ predicate on the "agent_id" field.
func AgentIDNEQ(v int) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNEQ(FieldAgentID, v))
}

// AgentIDIn applies the In predicate on the "agent_id" field.
func AgentIDIn(vs ...int) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldIn(FieldAgentID, vs...))
}

// AgentIDNotIn applies the NotIn predicate on the "agent_id" field.
func AgentIDNotIn(vs ...int) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNotIn(FieldAgentID, vs...))
}

// AgentIDIsNil applies the IsNil predicate on the "agent_id" field.
func AgentIDIsNil() predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldIsNull(FieldAgentID))
}

// AgentIDNotNil applies the NotNil predicate on the "agent_id" field.
func AgentIDNotNil() predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNotNull(FieldAgentID))
}

// ErrorTypeEQ applies the EQ predicate on the "error_type" field.
func ErrorTypeEQ(v ErrorType) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldEQ(FieldErrorType, v))
}

// ErrorTypeNEQ applies the NEQ predicate on the "error_type" field.
func ErrorTypeNEQ(v ErrorType) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNEQ(FieldErrorType, v))
}

// ErrorTypeIn applies the In predicate on the "error_type" field.
func ErrorTypeIn(vs ...ErrorType) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldIn(FieldErrorType, vs...))
}

// ErrorTypeNotIn applies the NotIn predicate on the "error_type" field.
func ErrorTypeNotIn(vs ...ErrorType) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNotIn(FieldErrorType, vs...))
}

// ErrorTypeIsNil applies the IsNil predicate on the "error_type" field.
func ErrorTypeIsNil() predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldIsNull(FieldErrorType))
}

// ErrorTypeNotNil applies the NotNil predicate on the "error_type" field.
func ErrorTypeNotNil() predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNotNull(FieldErrorType))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.AuditRecord {
	return predicate.AuditRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.AuditRecord {
	return predicate.AuditRecord(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAction applies the HasEdge predicate on the "action" edge.
func HasAction() predicate.AuditRecord {
	return predicate.AuditRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ActionTable, ActionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasActionWith applies the HasEdge predicate on the "action" edge with a given conditions (other predicates).
func HasActionWith(preds ...predicate.ActionModel) predicate.AuditRecord {
	return predicate.AuditRecord(func(s *sql.Selector) {
		step := newActionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAgent applies the HasEdge predicate on the "agent" edge.
func HasAgent() predicate.AuditRecord {
	return predicate.AuditRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AgentTable, AgentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAgentWith applies the HasEdge predicate on the "agent" edge with a given conditions (other predicates).
func HasAgentWith(preds ...predicate.Agent) predicate.AuditRecord {
	return predicate.AuditRecord(func(s *sql.Selector) {
		step := newAgentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AuditRecord) predicate.AuditRecord {
	return predicate.AuditRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AuditRecord) predicate.AuditRecord {
	return predicate.AuditRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AuditRecord) predicate.AuditRecord {
	return predicate.AuditRecord(sql.NotPredicates(p))
}
