// Code generated by ent, DO NOT EDIT.

package auditrecord

import (
	"go-backend-template/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldLTE(FieldID, id))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldEQ(FieldProjectID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldEQ(FieldUserID, v))
}

// Prompt applies equality check predicate on the "prompt" field. It's identical to PromptEQ.
func Prompt(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldEQ(FieldPrompt, v))
}

// Validated applies equality check predicate on the "validated" field. It's identical to ValidatedEQ.
func Validated(v bool) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldEQ(FieldValidated, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNotIn(FieldProjectID, vs...))
}

// ProjectIDGT applies the GT predicate on the "project_id" field.
func ProjectIDGT(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldGT(FieldProjectID, v))
}

// ProjectIDGTE applies the GTE predicate on the "project_id" field.
func ProjectIDGTE(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldGTE(FieldProjectID, v))
}

// ProjectIDLT applies the LT predicate on the "project_id" field.
func ProjectIDLT(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldLT(FieldProjectID, v))
}

// ProjectIDLTE applies the LTE predicate on the "project_id" field.
func ProjectIDLTE(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldLTE(FieldProjectID, v))
}

// ProjectIDContains applies the Contains predicate on the "project_id" field.
func ProjectIDContains(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldContains(FieldProjectID, v))
}

// ProjectIDHasPrefix applies the HasPrefix predicate on the "project_id" field.
func ProjectIDHasPrefix(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldHasPrefix(FieldProjectID, v))
}

// ProjectIDHasSuffix applies the HasSuffix predicate on the "project_id" field.
func ProjectIDHasSuffix(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldHasSuffix(FieldProjectID, v))
}

// ProjectIDEqualFold applies the EqualFold predicate on the "project_id" field.
func ProjectIDEqualFold(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldEqualFold(FieldProjectID, v))
}

// ProjectIDContainsFold applies the ContainsFold predicate on the "project_id" field.
func ProjectIDContainsFold(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldContainsFold(FieldProjectID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldContainsFold(FieldUserID, v))
}

// PromptEQ applies the EQ predicate on the "prompt" field.
func PromptEQ(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldEQ(FieldPrompt, v))
}

// PromptNEQ applies the NEQ predicate on the "prompt" field.
func PromptNEQ(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNEQ(FieldPrompt, v))
}

// PromptIn applies the In predicate on the "prompt" field.
func PromptIn(vs ...string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldIn(FieldPrompt, vs...))
}

// PromptNotIn applies the NotIn predicate on the "prompt" field.
func PromptNotIn(vs ...string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNotIn(FieldPrompt, vs...))
}

// PromptGT applies the GT predicate on the "prompt" field.
func PromptGT(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldGT(FieldPrompt, v))
}

// PromptGTE applies the GTE predicate on the "prompt" field.
func PromptGTE(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldGTE(FieldPrompt, v))
}

// PromptLT applies the LT predicate on the "prompt" field.
func PromptLT(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldLT(FieldPrompt, v))
}

// PromptLTE applies the LTE predicate on the "prompt" field.
func PromptLTE(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldLTE(FieldPrompt, v))
}

// PromptContains applies the Contains predicate on the "prompt" field.
func PromptContains(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldContains(FieldPrompt, v))
}

// PromptHasPrefix applies the HasPrefix predicate on the "prompt" field.
func PromptHasPrefix(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldHasPrefix(FieldPrompt, v))
}

// PromptHasSuffix applies the HasSuffix predicate on the "prompt" field.
func PromptHasSuffix(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldHasSuffix(FieldPrompt, v))
}

// PromptEqualFold applies the EqualFold predicate on the "prompt" field.
func PromptEqualFold(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldEqualFold(FieldPrompt, v))
}

// PromptContainsFold applies the ContainsFold predicate on the "prompt" field.
func PromptContainsFold(v string) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldContainsFold(FieldPrompt, v))
}

// ProposedActionIsNil applies the IsNil predicate on the "proposed_action" field.
func ProposedActionIsNil() predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldIsNull(FieldProposedAction))
}

// ProposedActionNotNil applies the NotNil predicate on the "proposed_action" field.
func ProposedActionNotNil() predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNotNull(FieldProposedAction))
}

// ValidatedEQ applies the EQ predicate on the "validated" field.
func ValidatedEQ(v bool) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldEQ(FieldValidated, v))
}

// ValidatedNEQ applies the NEQ predicate on the "validated" field.
func ValidatedNEQ(v bool) predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNEQ(FieldValidated, v))
}

// FinalResponseIsNil applies the IsNil predicate on the "final_response" field.
func FinalResponseIsNil() predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldIsNull(FieldFinalResponse))
}

// FinalResponseNotNil applies the NotNil predicate on the "final_response" field.
func FinalResponseNotNil() predicate.AuditRecord {
	return predicate.AuditRecord(sql.FieldNotNull(FieldFinalResponse))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AuditRecord) predicate.AuditRecord {
	return predicate.AuditRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AuditRecord) predicate.AuditRecord {
	return predicate.AuditRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AuditRecord) predicate.AuditRecord {
	return predicate.AuditRecord(sql.NotPredicates(p))
}
